// GET Categories
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_PENDING = "GET_CATEGORIES_PENDING";

// GET Articles
export const GET_ARTICLES = "GET_ARTICLES";
export const GET_ARTICLES_PENDING = "GET_ARTICLES_PENDING";

// GET Latest Articles
export const GET_LATEST_ARTICLES = "GET_LATEST_ARTICLES";
export const GET_LATEST_ARTICLES_PENDING = "GET_LATEST_ARTICLES_PENDING";

// GET Article by Category
export const GET_ARTICLES_BY_CAT = "GET_ARTICLES_BY_CAT ";
export const GET_ARTICLES_BY_CAT_PENDING = "GET_ARTICLES_BY_CAT_PENDING";

// GET Article by Category
export const GET_ARTICLES_DETAIL = "GET_ARTICLES_DETAIL ";
export const GET_ARTICLES_DETAIL_PENDING = "GET_ARTICLES_DETAIL_PENDING";
